### ISSUE TITLE
Windows shortcut to lock screen is not working

### ISSUE THREAD

**Issue by KculSpam** [Martenfur/TabletFriend#26]
The shortcut, win+L, that I use to lock my screen and switch users is not working on TabletFriend and is only typing the letter L. The shortcut works fine on my physical keyboard.

**Comment by nrome-n** [comment]
i have the same issue

**Comment by Martenfur** [comment]
My guess is that those are admin actions and Windows doesn't let non-admin apps to access them. You can't do ctrl+alt_del for example.

One workaround is to do this:

```yaml
	sleep:
		text: sleep
		actions: 
			- win+x
			- u
			- s
		size: 2,2
```

This will put the computer to sleep. If it's inconsistent, try adding a small delay between each action.
