### ISSUE TITLE
How to align these buttons?

### ISSUE THREAD

**Issue by attemptedcode** [Martenfur/TabletFriend#39]
Hey, thanks for creating a wonderful alternative to other (costly) programs.

I understand that buttons auto-align. I'm trying to top align the right arrow button to the up arrow - is that possible?

![tabletfriend](https://github.com/Martenfur/TabletFriend/assets/160088364/a5271fa0-1cbc-4ed0-957e-cd9ad8d20f46)

```
layout_width: 4
button_size: 24
margin: 8

left:
    action: left
    icon: arrow_left_thick
    size: 1,2

  up:
    action: up
    icon: arrow_up_thick
    size: 2,1

  down:
    action: down
    icon: arrow_down_thick
    size: 2,1

  right:
    action: right
    icon: arrow_right_thick
    size: 1,2
```
