### ISSUE TITLE
some oem_ keys default to comma

### ISSUE THREAD

**Issue by Hifilo** [Martenfur/TabletFriend#55]
**IMPORTANT**: Before you ask a question, make sure you carefully read the README and looked through the list of all available keys: https://github.com/Martenfur/TabletFriend/blob/develop/docs/keys.md

trying to make my own toolbar, and found that oem_period registers as comma. oem_pipe also registers as comma.

When I set this kind of action it also creates a default icon for the enter key. 

If you look at the `prev_brush` which i set `action: oemcomma` that command seems to work as intended. It doesn't matter if I have this commented out, the result is the same.

Any assistance is appreciated.

Here is the profile
```yaml


layout_width: 4
button_size: 10
margin: 8

app: Photoshop

buttons:
	undo:
		action: ctrl+z
		size: 2,2
		style: accent
		icon: undo
		text: undo

	redo:
		action: ctrl+y
		size: 2,2
		style: accent
		icon: redo
		text: redo

	next_brush:
		action: oem_pipe
		size: 2,2
		style: accent
		text: next_brush

	magic_wand:
		action: w
		size: 2,2
		style: accent
		icon: auto-fix
		text: magic_wand_tool

	prev_brush:
		 action: oemcomma
		 size: 2,2
		 style: accent
		 icon: transfer-left
		 text: prev_brush

	docked_spacer1:
		spacer: true
		visibility: docked
		size: 4,1



	selection_tool:
		action: m
		size: 2,2
		style: accent
		icon: selection-drag
		text: rectangle_selection_tool

	cut:
		action: ctrl+x
		size: 2,2
		style: accent
		icon: content_cut
		text: cut

	copy:
		action: ctrl+c
		size: 2,2
		style: accent
		icon: content_copy
		text: copy


	paste:
		action: ctrl+v
		size: 2,2
		style: accent
		icon: content_paste
		text: paste

	make_material:
		action: ctrl+shift+n
		size: 2,2
		text: make material
		icon: image-plus


	docked_spacer2:
		spacer: true
		visibility: docked
		size: 4,1


	# space:
		# action: toggle space
		# size: 2,2
		# text: toggle space
		# icon: keyboard_space
	# ctrl:
		# action: toggle ctrl
		# size: 2,2
		# text: toggle ctrl
		# icon: apple_keyboard_control
	# alt:
		# action: toggle alt
		# size: 2,2
		# text: toggle alt
		# icon: apple_keyboard_option

	docked_spacer3:
		spacer: true
		visibility: docked
		size: 4,1

	next_brush:
		action: oemcomma
		size: 2,2
		style: outlined
		icon: subdirectory_arrow_left

	docked_spacer4:
		spacer: true
		visibility: docked
		size: 4,1

	enter:
		action: enter
		size: 2,2
		style: outlined
		icon: subdirectory_arrow_left # this was the cause of the issue
	escape:
		font_weight: 500
		action: escape
		size: 2,2
		style: outlined
		text: Esc

	docked_spacer5:
		spacer: true
		visibility: docked
		size: 4,1

	new_layer:
		action: ctrl+shift+n
		size: 2,2
		icon: layers-plus
		style: accent
		text: create new layer

	duplicate:
		action: ctrl+j
		size: 2,2
		icon: content-duplicate
		style: accent
		text: duplicate layer

	merge:
		action: ctrl+e
		size: 4,2
		icon: layers
		style: accent
		text: merge with layer below

	spacer1:
		spacer: true
		size: 4,1
 
	transform:
		action: ctrl+t
		size: 2,2
		style: outlined
		icon: vector-rectangle
		text: transform

	M:
		action: m
		size: 2,4
		style: outlined 
		icon: select
		text: select (M)

	select all:
		action: ctrl+a
		size: 2,2
		style: outlined
		icon: select-all
		text: select all

	deselect:
		action: ctrl+d
		size: 2,2
		style: circular
		icon: checkbox-blank-off-outline
		text: deselect all

	V:
		action: v
		size: 2,2
		style: outlined
		icon: cursor-default
		text: click (V)

	B:
		action: b
		size: 2,4
		style: outlined
		icon: brush
		text: brush (B)

	invert-colors:
		action: x
		size: 2,2
		icon: invert-colors
		style: circular_accent
		text: switch colors

	G:
		action: g
		size: 2,2
		icon: format-color-fill
		style: outlined
		text: fill (G)

	E:
		action: e
		size: 2,2
		style: outlined
		icon: eraser
		text: erase (E)

	T:
		action: t
		size: 2,2
		icon: format-title
		style: outlined
		text: add text (T)

	spacer2:
		visibility: docked
		spacer: true
		size: 4,1

# Docking ===============================

	dock_toolbar_left1:
		icon: dock_left
		action: dock left
		text: dock left
		style: default
		visibility: docked_right
		size: 2,2

	undock_toolbar:
		icon: dock_top
		action: undock
		text: undock
		style: default
		visibility: docked
		size: 2,2

	dock_toolbar_right1:
		icon: dock_right
		action: dock right
		text: dock right
		style: default
		visibility: docked_left
		size: 2,2

	dock_toolbar_left:
		icon: dock_left
		action: dock left
		text: dock left
		style: default
		visibility: undocked
		size: 2,2

	dock_toolbar_right:
		icon: dock_right
		action: dock right
		text: dock right
		style: default
		visibility: undocked
		size: 2,2

	hide:
		action: hide
		size: 4,1
		icon: expand_more
		style: shy
		text: "hide"
```
and here is the toolbar of the code above:
![TabletFriend_cJe7OJotnJ](https://github.com/user-attachments/assets/24ff3041-430d-49c3-9ae8-4b3c7987f2b2)
